### ISSUE TITLE
CalcAtiMelt.py index out of range

### ISSUE THREAD

**Issue by Tich1212** [HydrologicEngineeringCenter/SnoPAC#1]
Using test dataset for Lilly Pond in DSSVue with 3.2.1.256

Exception in thread "AWT-EventQueue-0" Traceback (most recent call last):
  File "<string>", line 203, in recalcBtnSelect
  File "C:\Users\q0hecemt\AppData\Roaming\DSSVue\scripts\lib\ProcessPD.py", line 68, in processPairedData
    maxWyIndexList=max(wyLists,key=len)
ValueError: max of empty sequence
Exception in thread "AWT-EventQueue-0" Traceback (most recent call last):
  File "<string>", line 183, in recalcBtnSelect
  File "C:\Users\q0hecemt\AppData\Roaming\DSSVue\scripts\lib\CalcAtiMelt.py", line 47, in processPathsLists
    swePD.append    (p[0])
IndexError: index out of range: 0

**Comment by Tich1212** [comment]
https://github.com/HydrologicEngineeringCenter/SnoPAC/blob/3b68ead745bf3fbd44a809de0dc822fbf96ccdad/SnowMelt/lib/Locations.py#L92

Passing empty A parts so no paths are being read

**Comment by Tich1212** [comment]
https://github.com/HydrologicEngineeringCenter/SnoPAC/blob/3b68ead745bf3fbd44a809de0dc822fbf96ccdad/SnowMelt/lib/Locations.py#L61-L68

A and B parts are coming from this dict builder

**Comment by Tich1212** [comment]
resolved with 482ba98
